disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - file_length
  - type_body_length

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

excluded:
  - Pods
  - Carthage
  - DerivedData

force_cast: warning
force_try: warning
force_unwrapping: warning

identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - hr
    - ts

type_name:
  min_length: 3
  max_length: 40

custom_rules:
  comments_space:
    name: "Space After Comment"
    regex: '//\S'
    message: "There should be a space after //"
    severity: warning
