name: Halo
options:
  bundleIdPrefix: com.yannis
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: "15.0"
  createIntermediateGroups: true
targets:
  Halo:
    type: application
    platform: iOS
    sources:
      - path: Halo
    info:
      path: Halo/Info.plist
      properties:
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchStoryboardName: ""
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yannis.halo
        DEVELOPMENT_TEAM: "" # Add your team ID here
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: 1
    
  HaloTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: HaloTests
    dependencies:
      - target: Halo
    info:
      path: HaloTests/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yannis.halo.tests
        DEVELOPMENT_TEAM: "" # Add your team ID here
        CODE_SIGN_STYLE: Automatic
